### ISSUE TITLE
[BUG] Multiplayer Long Rest issues.

### ISSUE THREAD

**Issue by VladParshin** [Squidpad/BG3DevouringAndDigesting#16]
**Describe the bug**
In Multiplayer,  when consuming another player's (non-host/main) character, the main character cannot initiate a long rest. Long Rest must be initiated by another party, who is devoured. This leads to a situation, where, if the other player's character is digested, a long-rest cannot be initiated without resetting the devouring plugin.

**To Reproduce**
1) As the host/game owner, have another person join your game
2) Upon consuming the character, long rest may not be initiated by main character
3) Devoured party has to initiate rest. OR. If Digesting the other player, the option to long rest cannot be clicked.

**Expected behavior**
Long Rest should be initiated by the main party leader/host, with confirmation from other parties

**Screenshots**

**Requirements Versions**
Script Extender:
SE v18
Baldur's Gate 3 Mod Manager: 
1.0.10.0
Mod Configuration Menu:
1.9.0.0

**Load Order**
<attached>

**Additional context**
None

[Current_28-07-2024_18-02-35.json](https://github.com/user-attachments/files/16402570/Current_28-07-2024_18-02-35.json)

**Comment by Mr12451** [comment]
Turned the long rest spell into a potion (located in the bag of vore items). It can be drank by any party member to start long rest. Dunno if this fixes the issue, we'll see.
