### ISSUE TITLE
[BUG] New Warlock Subclass cannot use spells once they gain spell slots higher than the custom spells

### ISSUE THREAD

**Issue by smeargle99** [Squidpad/BG3DevouringAndDigesting#18]
When a Great Hunger Warlock levels up, if their spell slots are higher than the level of the new spells added by the mod, they cannot use them.

1. Take Frog's Tongue Spell at level up
2. Gain Warlock slots above level 1
3. You will not be able to cast Frog's tongue any more

**Expected behavior**
Custom warlock spells should have an upcast version for higher levels

**Screenshots**
![image](https://github.com/user-attachments/assets/a3678525-fe61-487c-adcc-1d5a43063415)

**Requirements Versions**
Script Extender:
V20
Baldur's Gate 3 Mod Manager: 
1.0.11.1
Mod Configuration Menu:
1.15.1.0

**Load Order**
[Current_9-19-2024_09-41-08.json](https://github.com/user-attachments/files/17062245/Current_9-19-2024_09-41-08.json)

**Additional context**
Apologies if any of this is wrong or too much for a problem you already know about

**Comment by Mr12451** [comment]
Added upcasting for the spells, this should fix the issue
