### ISSUE TITLE
[BUG] Rescue spell can't be cast by warlock past lvl 2 spell slots. v4.3.1

### ISSUE THREAD

**Issue by SolPhyx** [Squidpad/BG3DevouringAndDigesting#24]
**Describe the bug**
When attempting to cast the Rescue spell as warlock with lvl 2 spell slots the spell gives you multiple options for the rescue locus. However, if you have a lvl 3 and above spell slot for warlock you are unable to cast the spell as it no longer offers you a choice of locus.

**To Reproduce**

1. Acquire the Rescue spell for Warlock.
2. Reach level 5.
3. Attempt to cast the Rescue spell with upgraded spell slots.
4. Observe spell no longer offers options for casting.

**Expected behavior**
I assume that the spell should still allow you to choose what locus you want to use and then let you cast it despite having a higher level spell slot.

**Screenshots**
lvl 2 spell slots
![image](https://github.com/user-attachments/assets/6041d320-9296-47e8-a5b9-076512376be9)
![image](https://github.com/user-attachments/assets/fba1094d-3e54-49eb-98f5-f5b2299e4447)
lvl 3 spell slots
![image](https://github.com/user-attachments/assets/c50fa3c1-6602-4663-a99e-6727ecd8838c)
![image](https://github.com/user-attachments/assets/f2b5030c-d4e6-4768-90bd-c36476034485)

**Requirements Versions**
Script Extender:
(v20)
Baldur's Gate 3 Mod Manager: 
(1.0.11.1)
Mod Configuration Menu:
(1.13.0.1)

**Load Order**
[LoadOrder.json](https://github.com/user-attachments/files/17271799/LoadOrder.json)

**Comment by Mr12451** [comment]
I know why this happens, I'll fix it in the future updates

**Comment by SolPhyx** [comment]
Upcasting now works however, you when trying to target anyone it considers them an invalid target, regardless of if you upcast or not. I'm not sure if I'm missing something though.

**Comment by Mr12451** [comment]
I couldn't reproduce the issue. What spell doesn't work?

**Comment by SolPhyx** [comment]
I will attempt to reproduce the issue and I will give a more detailed set of steps to reproduce in a new bug report. If I can't get it to happen you won't hear from me.
