### ISSUE TITLE
[BUG] Unable to load saves or start new game with Patch 7

### ISSUE THREAD

**Issue by DrakinHydra** [Squidpad/BG3DevouringAndDigesting#26]
Every time I try to open an old save (whether or not it had the mod installed) it loads for a bit then I get this message "We were unable to start a new game. this might be because of the mods... Pleas disable external mods and try again" and get put back in the main menu. I first believed it was because of a conflict with some mods I have, but after disabling every mod aside from Devouring, Mod Fixer, and MCM, the message still appears. I believe this may be because of Patch 7 not being compatible with this mod, I speculate this because I don't know what else could be causing this to happen.

**To Reproduce**
1. Open The game
2. Load Save/ New Game
3. Wait to load

**Expected behavior**
I believe it should normally be able to load either old saves or a new save, and play the game

**Requirements Versions**
Script Extender: v20
Baldur's Gate 3 Mod Manager: 1.0.11.1
Mod Configuration Menu: 1.17.1.0

**Load Order**
[load Order.txt](https://github.com/user-attachments/files/17357342/load.Order.txt)

**Comment by Mr12451** [comment]
I've heard that the old mod fixer could be the issue, so I removed it in the new release. See if it helps

**Comment by DrakinHydra** [comment]
That was the issue. Now I am able to start up new, old, and create games now. And as far as I can tell, it functions as intended, Thank you
