### ISSUE TITLE
Syntax errors Appearing after game launch

### ISSUE THREAD

**Issue by Banepal** [Squidpad/BG3DevouringAndDigesting#6]
After i installed the mod and followed through all the steps on the main page and the Lua debugger link  then launch the game syntax errors appeared in BootstrapServer.lua, VoreUtils.lua and Output.lua. I tried reinstalling and crosschecking for improper installation but all sets were identical.

**Comment by Squidpad** [comment]
This is from a very old build, and should be fixed in the current release.
